### ISSUE TITLE
'M_PI' is deprecated in Xcode 8.3

### ISSUE THREAD

**Issue by nelsballs** [HamzaGhazouani/HGCircularSlider#12]
Using Xcode 8.3, I have several swift compiler warnings : 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

**Comment by frederik-jacques** [comment]
This has been fixed in #11 , but the Pod still has to be updated.
@HamzaGhazouani , is it possible to update the pod?

Thanks!

**Comment by HamzaGhazouani** [comment]
Done guys!
