### ISSUE TITLE
why xcode8 error?

### ISSUE THREAD

**Issue by CoderYLZhang** [HamzaGhazouani/HGCircularSlider#2]
![image](https://cloud.githubusercontent.com/assets/13221319/20878727/71343350-bb0b-11e6-8d70-4de45cec2ce2.png)

xcode8 with  HGCircularSlider 1.0.2
what can i do ?

**Comment by CoderYLZhang** [comment]
![image](https://cloud.githubusercontent.com/assets/13221319/20879284/fc23296a-bb0d-11e6-9246-be4e51b48cef.png)
resolved

**Comment by CoderYLZhang** [comment]
![image](https://cloud.githubusercontent.com/assets/13221319/20879471/e9a8b20e-bb0e-11e6-9aef-862d1c135cf3.png)
but how can i do this like your dome?

**Comment by HamzaGhazouani** [comment]
Hi @CoderYLZhang,

If your project is in Swift 3 and you use Xcode 8, normally you don't need to do any change.
Where you find "Unsupported Version 3.0"? why you need to have this in your project ? your project build successfully after changing "Use Legacy Swift Language Version" to 'No' ?

Thanks a lot
