### ISSUE TITLE
Disable touch?

### ISSUE THREAD

**Issue by FouadAstitou** [HamzaGhazouani/HGCircularSlider#23]
Hi Hamza,

It seems i can't find the documentation.

My question: Can we disable touch on the Circularslider?

**Comment by HamzaGhazouani** [comment]
Hi Fouad, 
Yes you can disable touch by using  [isUserInteractionEnabled](https://developer.apple.com/documentation/uikit/uiview/1622577-isuserinteractionenabled):
`circularSlider.isUserInteractionEnabled = false`

The CircularSlider [Documentation](http://cocoadocs.org/docsets/HGCircularSlider/2.0.0/index.html)

**Comment by FouadAstitou** [comment]
Thanks for the quick reply brother. I figuered out that my issue is not because of the CircularSlider.

Keep up the good work brother.

Verstuurd vanaf mijn iPhone

**Comment by HamzaGhazouani** [comment]
You are welcome @FouadAstitou :)
