### ISSUE TITLE
Remove padding

### ISSUE THREAD

**Issue by Natelegreat1** [HamzaGhazouani/HGCircularSlider#25]
Hello!

Is there a way to remove excess padding from the HGCircularSlider view?

<img width="294" alt="screen shot 2017-10-03 at 2 14 51 am" src="https://user-images.githubusercontent.com/2666640/31112314-fda6d8ac-a7e0-11e7-9490-4e29486200e4.png">

**Comment by HamzaGhazouani** [comment]
Hi @Natelegreat1, you can fix that by setting `backtrackLineWidth`equal to `lineWidth`

**Comment by Natelegreat1** [comment]
@HamzaGhazouani Good thinking but alas I do not mean the fact that the dark blue is thicker than the white part -- that, I want! :) 
What I would like to get rid of is where I've drawn red lines. I want the HGCircularSlider UIView to siteToFit() to its containing view. Does that make more sense?

**Comment by HamzaGhazouani** [comment]
Hi @Natelegreat1, we have this padding because the thumbs (in the circular slider) should be inside the frame. Below, how we calculate the radius of the circular slider 
```
/**
* The radius of circle
*/
    internal var radius: CGFloat {
        get {
            // the minimum between the height/2 and the width/2
            var radius =  min(bounds.center.x, bounds.center.y)
            // all elements should be inside the view rect, for that we should subtract the highest value between the radius of thumb and the line width
            radius -= max(lineWidth, (thumbRadius + thumbLineWidth))
            return radius
        }
    }
```
in your case, we use it like a progress view, so we don't need the thumbs
If you put `thumbRadius = 0` & `thumbLineWidth = 0` the padding will disappear.

Thanks

**Comment by Natelegreat1** [comment]
Amazing. That's exactly what I was looking for!
