### ISSUE TITLE
i want Objc  

### ISSUE THREAD

**Issue by lotus-lotus** [HamzaGhazouani/HGCircularSlider#27]

**Comment by HamzaGhazouani** [comment]
Hi @lotus-lotus, can you please explain your issue?

**Comment by lotus-lotus** [comment]
I think there is a 50 degree distance between the top and the end slider.
I haven ' t read about specific proportions
I hope to get help

Forgive me for being a beginner.
发自我的 iPhone

**Comment by HamzaGhazouani** [comment]
Can you please share your code ?

**Comment by lotus-lotus** [comment]
I write your code directly.Improved on your basis

发自我的 iPhone

**Comment by lotus-lotus** [comment]
It has been sent to your mailbox, I hope to see it for me.

**Comment by HamzaGhazouani** [comment]
Hi @lotus-lotus, I did not receive your email, can I please give more details ? thanks
