### ISSUE TITLE
Trying to make slider to have stop position on top so that thumb wouldn't keep sliding

### ISSUE THREAD

**Issue by alexgofman** [HamzaGhazouani/HGCircularSlider#29]
Hi, I am not sure if someone made this feature but I cannot solve it myself...

Any thoughts on how to have stop position and have lets say starting point on top from 0 and goes to 100 and stops so I would not be able to move slider further

Advise would be much appreciated. Thank you
@HamzaGhazouani

**Comment by HamzaGhazouani** [comment]
Hi @alexgofman, sorry for my late answer 
for now, we don't have this feature yet #10 , if you resolved this a PR will be really appreciated
Hamza
