### ISSUE TITLE
thumb slider freezes or touches at outside of round slider thumb control automatically

### ISSUE THREAD

**Issue by alexgofman** [HamzaGhazouani/HGCircularSlider#33]
Hey,

Could you please give me a hint how to fix following problem:

when tap on the slider thump it freezes and doesn't move or seems like thumb control is not on the round thumb itself, because it slides to the side

thanks

**Comment by HamzaGhazouani** [comment]
Hey @alexgofman, can you give more details please, if you can upload a video it will be super, thanks a lot

**Comment by HamzaGhazouani** [comment]
Hey @alexgofman, I will close the ticket for now. If you get the chance to look into this issue further, you can always respond to reopen the ticket
