### ISSUE TITLE
Error: "Failed to render and update auto layout status..."

### ISSUE THREAD

**Issue by mattHorrigan** [HamzaGhazouani/HGCircularSlider#34]
Following the setup instructions produces the result "Failed to render and update auto layout status..." when I try to change the class of a View to "Circular Slider" or any of the others provided.  Running OS 10.12.6.  The circular slider does not appear and indeed no functionality seems to work.

**Comment by mattHorrigan** [comment]
Solved it with some changes to the podfile, following these: `https://stackoverflow.com/questions/39732312/xcode-8-ib-designables-failed-to-render-and-update-auto-layout-status-the-a` and `https://github.com/Skyscanner/SkyFloatingLabelTextField/issues/201#issuecomment-381915911`.

**Comment by HamzaGhazouani** [comment]
Thanks @mattHorrigan for using the lib and for your contribution :)
