### ISSUE TITLE
Updates for iOS12/XCode 10/Swift 4.2?

### ISSUE THREAD

**Issue by johnbanks** [HamzaGhazouani/HGCircularSlider#36]
I am having rendering issues, any chance this wonderful package will be updated for the new stuff?  Thanks.

**Comment by HamzaGhazouani** [comment]
Hi @johnbanks, I will update the project soon.
If you would like to contribute don't hesitate, I will be happy to see your PRs.

**Comment by HamzaGhazouani** [comment]
Done

**Comment by nmullaney** [comment]
Is there an updated cocoa pod for this?  Thanks!

**Comment by HamzaGhazouani** [comment]
thanks @nmullaney  for reporting, I updated the pod, the new version 2.1.0 is available
