### ISSUE TITLE
How to set mid thumb position programatically?

### ISSUE THREAD

**Issue by gargDiGrt** [HamzaGhazouani/HGCircularSlider#4]
In other example type of view.
I want to display mid thumb point at specific point when view controller appear. How can I do this ?

**Comment by HamzaGhazouani** [comment]
Hi gargDiGrt, 
You should change the value of the property midPointValue.
In the version 1.0.2 this property was private, I changed to open in the version 1.0.3.
I updated also the example you can check it ;)
