### ISSUE TITLE
Track inner shadow & Gradient color support

### ISSUE THREAD

**Issue by libern** [HamzaGhazouani/HGCircularSlider#47]
How to achieve this?
1. gradient colour
2. track inner shadow

![image](https://user-images.githubusercontent.com/1830640/51959865-58c9f880-2491-11e9-9eeb-a5a64bfcf963.png)

**Comment by HamzaGhazouani** [comment]
Hi @libern, this feature is not supported yet

**Comment by HamzaGhazouani** [comment]
duplicated #8
