### ISSUE TITLE
Crash suddenly on assertion!

### ISSUE THREAD

**Issue by Raviojha62** [HamzaGhazouani/HGCircularSlider#6]
I am using this slider on a player and its working fine . but some time its automatically become crash and i am getting the reason in the console that 
assertion failed: Illegal interval: file /Users/sabakuch/Documents/Ravi/SlideMenu/Pods/HGCircularSlider/HGCircularSlider/Classes/CircularSliderHelper.swift, line 17

on line no 17 when i check
 assert(min <= max, NSLocalizedString("Illegal interval", comment: ""))

![screen shot 2017-01-04 at 5 00 29 pm](https://cloud.githubusercontent.com/assets/11419103/21641087/902680dc-d29f-11e6-8d52-8959b88d9aca.png)

**Comment by HamzaGhazouani** [comment]
Hey, 
I can't reproduce the crash in the player in the example.
Could please share how you configure the circular slider? 
Thanks

**Comment by Raviojha62** [comment]
Hi Hamza,
Thanks for reply...
I am getting this problem when network is slow down and songs become change . i mean when slider again start from beginning .

I was configured it with cocoapods and the language is swift 3.0

Below is the few part of code in the class in which slider is being use.

 // update the slider position and the timer text
    func updatePlayerUI(withCurrentTime currentTime: CGFloat) {
        circularSlider.endPointValue = currentTime
        var components = DateComponents()
        components.second = Int(currentTime)
        timeLbl.text = dateComponentsFormatter.string(from: components)
    }
    
    func updateTimer() {
        var components = DateComponents()
        components.second = Int(circularSlider.endPointValue)
        timeLbl.text = dateComponentsFormatter.string(from: components)
    }
    
    
    
    func togglePlayer(_ sender: UIButton) {
        switch sender.tag {
        case 0:
            let currentTime = Float64(circularSlider.endPointValue)
            let newTime = CMTimeMakeWithSeconds(currentTime, 600)
            audioPlayer.seek(to: newTime, toleranceBefore: kCMTimeZero, toleranceAfter: kCMTimeZero)
            audioPlayer.play()
        default:
            audioPlayer.pause()
        }
    }

**Comment by HamzaGhazouani** [comment]
I really can't reproduce the issue, but I think the problem is when you set the maximum value, sometimes is lower than the minimum value.
If you can share the code with issue in github I can look at it

**Comment by Raviojha62** [comment]
Hi Hamza , 
You are right, the maximum value some time set  0.0 and minimum value was higher . thats why its being crash . 
thanks for suggestion.

**Comment by HamzaGhazouani** [comment]
@Raviojha62  You are welcome :)
