### ISSUE TITLE
MidPointCircularSlider jumps when it circles through the max.

### ISSUE THREAD

**Issue by tommyyoon** [HamzaGhazouani/HGCircularSlider#60]
Is there anyway to make it so that it doesn't jump but goes through smoothly?

**Comment by HamzaGhazouani** [comment]
Hi @tommyyoon, the mid point circular slider can't take a value between the max and min, it's for that it jumps

**Comment by HamzaGhazouani** [comment]
Hey @tommyyoon, I will close the ticket for now. If you get the chance to look into this issue further, you can always respond to reopen the ticket
