### ISSUE TITLE
Help: 12 Hours clock with AM/PM support

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [HamzaGhazouani/HGCircularSlider#7]
Hello @HamzaGhazouani,

Thank you for sharing your work.
I am using this control in an app. The feature requires to show 12 hours clock (like regular wall clock) but the user can opt AM/PM. Like user can choose to sleep from 10 PM to 6 AM or 10 AM to 6 PM.

Can you please give me an insight n how to do this?
Your help is very much appreciated. TIA :)

**Comment by HamzaGhazouani** [comment]
Hello @AnnieNinaJoyceV,
Do you look for something like iOS native alarm? (Like the first example in the sample code but using 12 hours instead 24h, right?) 
If you could share a screenshot of what you need, it will be perfect :)

**Comment by AnnieNinaJoyceV** [comment]
@HamzaGhazouani Yes, I want it to work exactly like the iOS 10 Bedtime. Is it possible?

**Comment by HamzaGhazouani** [comment]
@AnnieNinaJoyceV Sorry for my late response.
To do that we need to have the number of  rounds to rich the maximum value.
minValue: 0, maxValue: 24,  and the number of round should be 2
the first round we will reach 12am, the second one it will be midnight.

Please checkout this fork it works perfectly. [https://github.com/amichnia/HGCircularSlider](url)
And I will integrate this feature soon.

**Comment by AnnieNinaJoyceV** [comment]
@HamzaGhazouani Thanks, I will check this out!

**Comment by HamzaGhazouani** [comment]
Fixed in #15
